#!/bin/bash

# path to the toggle file
path="/dev/shm/toggle_backlight"

read old < "${path}";

if [[ "$old" -gt 0 ]]; then
    read a < /sys/class/backlight/nv_backlight/brightness;
    echo "$a%";
fi
