#!/bin/bash

path="/dev/shm/toggle_cpu_percent"

read old < "${path}";

if [[ "$old" -gt 0 ]]; then

    usage=`grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print substr(usage, 0,6)}'`
    echo $usage% 
    echo $usage% 

    if [[ $QUALITY -ge 80 ]]; then
        echo "#00FF00"
    elif [[ $QUALITY -lt 80 ]]; then
        echo "#FFF600"
    elif [[ $QUALITY -lt 60 ]]; then
        echo "#FFAE00"
    elif [[ $QUALITY -lt 40 ]]; then
        echo "#FF0000"
    fi
fi
