#!/bin/bash

# path to store the old results in
path="/dev/shm/$(basename $0)"

if ! [[ -f "${path}" ]]; then
  echo "1" > "${path}"
  chmod 0666 "${path}"
fi

read old < "${path}";

#parse old
#old=(${old//;/ })
#old=$old[0]

if [[ "$old" -gt 0 ]]; then
    echo -n "<span color='#FFA1F2'></span>";
    echo "0" > "${path}";
else
    echo -n "<span color='#FFA1F2'></span>";
    echo "1" > "${path}";
fi

