'Video':
  'Monitor Idx': '0'
  'Width': '1600'
  'Height': '900'
  'Bits Per Pixel': '32'
  'Full Screen': '1'
  'Vertical Sync': '0'
  'Border Less': '0'
  'Texture Quality': '2'
  'Shader Quality': '2'
  'Glow': '1'
  'AQC': '0'
  'Dynamic Lights': '1'
  'Ship Colors': '1'
  'AA Mode': '-1'
  'AF Mode': '-1'
  'Gamma': '127'
  'Frame Finish': '0'
  'Hack FPS Replace Text': '0'
  'Lower AQC FrameRate': '10.000000'
  'Upper AQC FrameRate': '25.000000'
  'Memory': '128'
'Audio':
  'Master Volume': '255'
  'SFX Volume': '255'
  'Voice Volume': '205'
  'Music Volume': '215'
'Input':
  'Mouse Grab': '1'
  'Mouse Invert Tilt': '1'
  'Mouse Swap Rudder with Steering': '0'
  'Joy Index': '0'
  'Joy 1X Src': '0'
  'Joy 1Y Src': '1'
  'Joy 2X Src': '2'
  'Joy 2Y Src': '3'
  'Joy Rudder Src': '5'
  'Joy Throttle Src': '4'
  'Joy 1X Scale': '1.000000'
  'Joy 1Y Scale': '1.000000'
  'Joy 2X Scale': '1.000000'
  'Joy 2Y Scale': '1.000000'
  'Joy Rudder Scale': '1.000000'
  'Joy Throttle Scale': '1.000000'
  'Joy Button0 Src': '0'
  'Joy Button1 Src': '1'
  'Joy Button2 Src': '2'
  'Joy Button3 Src': '3'
  'Joy Button4 Src': '4'
  'Joy Button5 Src': '5'
  'Joy Button6 Src': '6'
  'Joy Button7 Src': '7'
  'Joy Button8 Src': '8'
  'Joy Button9 Src': '9'
  'Joy Button10 Src': '10'
  'Joy Button11 Src': '11'
  'Joy Button12 Src': '12'
  'Joy Button13 Src': '13'
  'Joy Button14 Src': '14'
  'Joy Button15 Src': '15'
  'Joy Button16 Src': '16'
  'Joy Button17 Src': '17'
  'Joy Button18 Src': '18'
  'Joy Button19 Src': '19'
  'Joy Button20 Src': '20'
  'Joy Button21 Src': '21'
  'Joy Button22 Src': '22'
  'Joy Button23 Src': '23'
  'Joy Button24 Src': '24'
  'Joy Button25 Src': '25'
  'Joy Button26 Src': '26'
  'Joy Button27 Src': '27'
  'Joy Button28 Src': '28'
  'Joy Button29 Src': '29'
  'Joy Use Rudder': '0'
  'Joy Use Throttle': '0'
  'Joy Use POV Hat': '0'
'Other':
  'Mod Name': ''
  'Capture Folder': 'screenshots'
  'Profile': 'default'
  'Player Logo Number': '0'
  'Player Logo Name': ''
